version: 1.0.{build}
image: Visual Studio 2015

platform:
- x86
- x64

init:
- ps: >-
    echo $env:PLATFORM

    if ($env:PLATFORM -eq "x86") {
      $Env:JAVA_HOME = "C:\Program Files (x86)\Java\jdk1.8.0"
      echo "32 Bit"
    }

    else {
      $Env:JAVA_HOME = "C:\Program Files\Java\jdk1.8.0"
      echo "64 bit"
    }

build_script:
- cmd: gradlew.bat build jacocoTestReport
    
after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- cmd: pip install codecov
- cmd: dir
- cmd: dir 
- cmd: dir build\reports
- cmd: dir build\reports\test
- cmd: codecov -f "SnobotRobotLibs/build/reports/jacoco/test/jacocoTestReport.xml"
